---
apiVersion: v1
kind: Namespace
metadata:
  name: $PREFIX-tier1
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: $PREFIX-tier1-gateway
  namespace: $PREFIX-tier1
spec:
  kubeSpec:
    service:
      type: LoadBalancer
      # This will be used to demo Tier1 w/ our sample app
      annotations:
        "external-dns.alpha.kubernetes.io/hostname": "demo-app.$PREFIX.workshop.cx.tetrate.info."
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend
  namespace: $PREFIX-tier1
spec:
  secretName: frontend-certs
  issuerRef:
    name: letsencrypt-dns-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - demo-app.$PREFIX.workshop.cx.tetrate.info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trafficgenerator
  name: trafficgenerator
  namespace: $PREFIX-tier1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: trafficgenerator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trafficgenerator
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - "while true; do curl -v https://demo-app.$PREFIX.workshop.cx.tetrate.info/proxy/\\?url\\=backend.$PREFIX.mesh\\&auth\\=\\&cachebuster\\=123456; sleep 10; done"
        image: appropriate/curl
        imagePullPolicy: Always
        name: trafficgenerator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always